### PR TITLE
Facelift Project

### PR DESCRIPTION
**Pull request by itbel**
* [x] **Navigation Bar**
* [x] **Events Directory**
* [ ] **Event Screen**
* [x] **People Directory**
* [ ] **Profile Screen**
* [x] **Groups Directory**
* [ ] **Group Screen**

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=794071576)

### CODE REVIEW

**Comment by lucastbelem** [comment]
@GeorgeBellTMH do we have that new environment up?

**Comment by GeorgeBellTMH** [comment]
I am having trouble verifying the credit card with AWS. I sent you an email about it. I think you have to call the bank to get them to approve it.

**Comment by GeorgeBellTMH** [comment]
Can you move this to a branch under the jesus-collective repo? I need to do some changes to get it running on AWS...

**Comment by itbel** [comment]
@GeorgeBellTMH Hey George I made a new branch and this PR is now targeting it. Do you need me to do anything?

**Pull request merged**
