### PR TITLE
Granular resource permissions

### PR DESCRIPTION
**Pull request by JonEsparaz**

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
I'm gonna do this now. Can you get one ready that defaults the create to allow verifiedUsers ... I'll update the existing in the backend, then Lucas can update them to whatever he wants once the permission control is added to the admin.

**Comment by JonEsparaz** [comment]
> Can you get one ready that defaults the create to allow verifiedUsers

I don't follow 100%. You mean a PR that updates the createResource mutation, right?

**Comment by GeorgeBellTMH** [comment]
Yah, it just needs to set it to something when creating or else the query fails...it could probably be an empty array, but I'd like to default to everyone being able to see the resource and then if Lucas wants to limit it further he can...

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH to clarify, we might have two different implementations in mind.

@lucastbelem and I determined that the download button is protected (anyone can view the page as a preview/market strategy). If you are not subscribed the download button says "Upgrade to download". If you click the button, a modal appears with instructions for upgrading your subscription.

Everyone is a verifiedUser, so the button would work for everyone. With that in mind, I'm going to do an empty array.

**Comment by GeorgeBellTMH** [comment]
No I understand, but the idea is that resources in general are public by default...the specific case of kids and youth is that they are hidden...so if they want to change it they can...this is the way it works for creating menu items, for creating groups, events etc...I want to keep it such that things are public, unless you make them not public...

**Comment by JonEsparaz** [comment]
I see. verifiedUser it is then.

**Comment by GeorgeBellTMH** [comment]
Schema updates are done.

**Comment by lucastbelem** [comment]
Thank you team! To make sure I follow, this will it possible for me to set a particular series group rather than just a page?

**Comment by JonEsparaz** [comment]
> Thank you team! To make sure I follow, this will it possible for me to set a particular series group rather than just a page?

Yes, when you click "Edit Resource", there will be a dropdown to select groups.

**Pull request merged**
