### PR TITLE
home-right card fixes

### PR DESCRIPTION
**Pull request by mmacedom**

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
Hey, we still need this to be a vertical carasol because the message component will go below it (it's disabled right now...but you can re-enable it to see the final layout...in src/constants.ts (set -SETTING_ISVISIBLE_conversation :true)

**Comment by GeorgeBellTMH** [comment]
You can also turn on SETTING_ISVISIBLE_organization and SETTING_ISVISIBLE_course to see what they will look like...

**Comment by GeorgeBellTMH** [comment]
(you might want to just turn them all on so you can see all the hidden functions)

**Comment by mmacedom** [comment]
@GeorgeBellTMH I see it now. I'll readjust the component above and limit the height so they can stack above each other

**Comment by mmacedom** [comment]
@GeorgeBellTMH I adjusted the components and turned off the conversation, organization, and courses components.

**Pull request merged**
