### PR TITLE
Added label to billing option picker

### LINKED ISSUE #675: Add line of text on billing choice
This comes from real user feedback. 5he dropdown with billing options wasn't super clear that it was a dropdown. Can we add a header for that billing that says *Select your billing option"? We could also change it from a dropdown to radio buttons where the user sees all 4 options at once, if that makes sense.

Please change the 90 day option to 85 days.

### PR DESCRIPTION
**Pull request by itbel**
- added label to freeDays picker, 
- changed 90 days to 85 days in options

resolves #675

### CODE REVIEW

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I think we still need to do whatever you did in the API to make Stripe update that trial to 85 days. @itbel only changed the label to 85 days.

**Comment by GeorgeBellTMH** [comment]
@itbel can you just make this calculate the number of days until March/April/May 1 and as we pass them remove them?

**Comment by itbel** [comment]
As per Lucas
only the 90-day option should decrement daily.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I need to this deployed to beta as soon as we can. Would you be able to publish today?

**Pull request merged**
