### PR TITLE
Add map to scrolling container

### LINKED ISSUE #146: Map: Lock to page for scroll
Can we make it so that when someone opens the map, it looks to the page so that if they scroll down without closing the map, it disappears, and reappears if they scroll back up? I'm thinking that people may try to scroll down and get frustrated when they try to scroll down because they'll have to close the map in order to view the dashboard properly.

### PR DESCRIPTION
**Pull request by JonEsparaz**
Resolves #146 

Edit: Lots of stuff in this PR after https://github.com/jesus-collective/mobile/pull/148/commits/c9c569bb5dc4d2c6d42f6a0fd031423d86eb3059

- Moves map inside scrolling container pretty much everywhere
- Adds mandatory prop `type` to all `<MyMap/>` components and optional `size` prop to most
- Adds prop `mapData` where missing (set as [] for now) 
- Displays all users on ProfilesScreen
- Displays all events on EventsScreen
- Displays event on EventScreen and set map centre to event location
- Hides map on GroupsScreen (#155)
- Displays group members and group owner on GroupScreen
- Adjusts MapSelector to zoom out and set map centre to `{lat: 0, lng: 0}` since this is where the draggable pin starts - hopefully people will realize they are in the middle of the ocean and actually move the pin
- Adds custom theme, custom marker to MapSelector
- Removes Street View and full screen from MapSelector 
- Keeps current user on map, but retains changes in #140

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
Might need to do this in a few places...

**Comment by JonEsparaz** [comment]
Working on it. Fixing some other stuff too (some of the maps aren't loading/displaying the data).

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH should be good to go.

**Comment by JonEsparaz** [comment]
After fixing a wild merge conflict - should be good to go.

**Comment by GeorgeBellTMH** [comment]
Sorry for that....lots of style changes today, and new JCComponent...hopefully sets us up for a better experience, more code re-use going forward...

**Comment by JonEsparaz** [comment]
No problem - my bad for not rebasing before making so many changes this evening.

**Pull request merged**
